version: '3'

services:
  database:
    container_name: ${POSTGRES_DOCKER_CONTAINER_NAME:-database}
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-groceries}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-not_default_pass}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./.docker/development/postgresql/data:/var/lib/postgresql/data:delegated
    ports:
      - ${POSTGRES_PORT:-5432}

  nginx:
    container_name: nginx-fruits
    build:
      context: ./.docker/development
      dockerfile: nginx.docker
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
    ports:
      - "8082:82"

  php-fpm:
    container_name: php-fpm
    depends_on:
      - database
    build:
      context: ./.docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./:/app

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
